### ISSUE TITLE
Quilt support

### ISSUE THREAD

**Issue by SplendidAlakey** [noriokun4649/TorchBowMod-fabric#2]
**Is your feature request related to a problem? Please describe.**

Currently, the mod crashes when used with [Quilt](https://quiltmc.org/) modloader.

Logs: https://gist.github.com/Footage2-Amply-Pounce/c70c63c970c98d3bfafabab3bcf15fcb

**Describe the solution you'd like**

Could you please make it compatible with Quilt?

**Describe alternatives you've considered**

-

**Additional context**

Usually, all Fabric mods are natively supported by Quilt, however, there are some exceptions when a mod needs some adjustments to work with it.

**Comment by noriokun4649** [comment]
I don't know much about Quilt modloader, what are the benefits of making it compatible?

**Comment by SplendidAlakey** [comment]
It is a fork of Fabric that provides more, advanced tools for developers to use. Currently, for mods that do not need to utilize these new tools, the only benefit of supporting Quilt is the fact that your mod will be accessible on it. Supporting Quilt also doesn't necessarily require you to maintain a separate project or drop support for Fabric, since Quilt aims to continue supporting all Fabric mods for the foreseeable future.

You will probably be better off asking for details on Quilt's discord server or something, since I'm not a developer myself. They could also most likely help you understand what exactly needs to be done to fix the current crash.

I love your mod and would be happy to have it in my modpack on Quilt, it's one of the only 4 Fabric mods I use, that currently don't work out of the box. However, I will understand it if you decide not to do it.

**Comment by noriokun4649** [comment]
Thanks for the explanation.

Currently, there is too little information (in Japan) and I am not sure if we can handle it.  
I can't make any promises, but I will give it a try.

**Comment by SplendidAlakey** [comment]
No problem, this is all I could really ask for :)

**Comment by SplendidAlakey** [comment]
Oh, and sorry for opening the issue in a wrong repository, I didn't realize that Fabric has separate one. You should be able to transfer this issue over to https://github.com/noriokun4649/TorchBowMod-fabric/issues

**Comment by noriokun4649** [comment]
@Footage2-Amply-Pounce 
Hi
I have loaded the Fabric version of the mod with Quilt Loader 0.17.3(MC1.19) and it seems to be working fine.
Looks like you have a few mods in there. Could you please find out which mods are in conflict?

**Comment by noriokun4649** [comment]
Oh, It doesn't seem to work with 1.19.2. Will investigate.

**Comment by SplendidAlakey** [comment]
Yep, sorry, forgot to mention that it's MC 1.19.2. There are no other mods, the list that you see in my crash report only consists of Fabric API and Quilt Standard Libraries modules, that count as "mods" in the logs. You get the same result when you load Fabric with just Fabric API, the logs will show about 50 "mods", even though they are just modules.

**Comment by noriokun4649** [comment]
I tried it with Quilt 0.17.3 +1.19.2 and it seems to work.
The fabric api is using 0.60.0 + 1.19.2.

<details>
  <summary>Loading log</summary>

  ```
[19:07:11] [main/INFO]: Loading Minecraft 1.19.2 with Quilt Loader 0.17.3
[19:07:12] [main/INFO]: Loading 52 mods:
	- fabric-api 0.60.0+1.19.2
	- fabric-api-base 0.4.11+e62f51a390
	- fabric-api-lookup-api-v1 1.6.9+9ff28f4090
	- fabric-biome-api-v1 9.0.17+aeb40ebe90
	- fabric-blockrenderlayer-v1 1.1.20+aeb40ebe90
	- fabric-client-tags-api-v1 1.0.1+b35fea8390
	- fabric-command-api-v1 1.2.11+f71b366f90
	- fabric-command-api-v2 2.1.7+0c17ea9690
	- fabric-commands-v0 0.2.28+df3654b390
	- fabric-containers-v0 0.1.34+df3654b390
	- fabric-content-registries-v0 3.2.3+aeb40ebe90
	- fabric-convention-tags-v1 1.1.1+7cd20a1490
	- fabric-crash-report-info-v1 0.2.5+aeb40ebe90
	- fabric-data-generation-api-v1 5.1.8+a680b9b490
	- fabric-dimensions-v1 2.1.30+aeb40ebe90
	- fabric-entity-events-v1 1.4.18+9ff28f4090
	- fabric-events-interaction-v0 0.4.28+aeb40ebe90
	- fabric-events-lifecycle-v0 0.2.28+df3654b390
	- fabric-game-rule-api-v1 1.0.21+aeb40ebe90
	- fabric-item-api-v1 1.5.7+35a03c4390
	- fabric-item-groups-v0 0.3.28+aeb40ebe90
	- fabric-key-binding-api-v1 1.0.20+aeb40ebe90
	- fabric-keybindings-v0 0.2.18+df3654b390
	- fabric-lifecycle-events-v1 2.1.2+aeb40ebe90
	- fabric-loot-api-v2 1.1.3+83a8659290
	- fabric-loot-tables-v1 1.1.6+9e7660c690
	- fabric-message-api-v1 5.0.3+176380a290
	- fabric-mining-level-api-v1 2.1.14+33fbc73890
	- fabric-models-v0 0.3.17+aeb40ebe90
	- fabric-networking-api-v1 1.2.4+5eb68ef290
	- fabric-networking-v0 0.3.21+df3654b390
	- fabric-object-builder-api-v1 4.0.11+aeb40ebe90
	- fabric-particles-v1 1.0.10+aeb40ebe90
	- fabric-registry-sync-v0 0.9.24+aeb40ebe90
	- fabric-renderer-api-v1 1.0.10+aeb40ebe90
	- fabric-renderer-indigo 0.6.12+aeb40ebe90
	- fabric-renderer-registries-v1 3.2.20+df3654b390
	- fabric-rendering-data-attachment-v1 0.3.14+aeb40ebe90
	- fabric-rendering-fluids-v1 3.0.7+aeb40ebe90
	- fabric-rendering-v0 1.1.22+df3654b390
	- fabric-rendering-v1 1.10.16+aeb40ebe90
	- fabric-resource-conditions-api-v1 2.0.11+e62f51a390
	- fabric-resource-loader-v0 0.6.1+aeb40ebe90
	- fabric-screen-api-v1 1.0.26+f05effaf90
	- fabric-screen-handler-api-v1 1.2.13+9ff28f4090
	- fabric-textures-v0 1.0.20+aeb40ebe90
	- fabric-transfer-api-v1 2.0.11+83a8659290
	- fabric-transitive-access-wideners-v1 1.3.0+42d99c3290
	- java 17
	- minecraft 1.19.2
	- quilt_loader 0.17.3
	- torchbowmod 1.0
  ```
</details>

![image](https://user-images.githubusercontent.com/17977166/185093672-aa3e629a-9efe-4cf9-84fb-af7151259938.png)
![image](https://user-images.githubusercontent.com/17977166/185093461-14017ff2-f655-4b10-b4a7-f9ba35b71dc2.png)

**Comment by noriokun4649** [comment]
> You get the same result when you load Fabric with just Fabric API

Oh, so sorry.

**Comment by SplendidAlakey** [comment]
Ah, seems like it is an incompatibility specifically with [QSL](https://modrinth.com/mod/qsl) then. QSL provides Quilt with Fabric API and its own set of tools. I never tested with the actual Fabric API, because I need QSL for other mods.

**Comment by noriokun4649** [comment]
Okay, I'll see if I can get it to work using QSL.

**Comment by noriokun4649** [comment]
We were able to confirm that it works with QSL. However, ~~it doesn't work with the one I downloaded from CurseForge. It's a mystery~~  :(
I found the cause. Oddly enough, it seems to crash if the mod has ```[]``` in the filename.

It has already been reported, so it seems we have to wait for Quilt to fix it.
https://github.com/QuiltMC/quilt-loader/issues/90

**Comment by SplendidAlakey** [comment]
Alright, thank you for looking into it!

For now, I suppose, I could just rename the file to remove the brackets.

And, since it's a Quilt issue and not your mod's, I'll close it. Sorry for kind of wasting your time.

**Comment by noriokun4649** [comment]
Np :)
It is nice to know a new modloader.
I will continue working on migrating from Fabric to the QSL API.

**Comment by noriokun4649** [comment]
Hi,
Uploaded the Quilt version of the file!
Some APIs have been changed to Quilt ones and are no longer compatible with Fabric, but you can check it out if you like.

[[1.19.x][Quilt]TorchBowMod_v1.0](https://www.curseforge.com/minecraft/mc-mods/torchbowmod/files/3939330)

**Comment by SplendidAlakey** [comment]
Yep, I saw it the moment it got uploaded and already downloaded. Thank you!
